name: Gerar Executável Windows

on: 
  push:
    branches: [ "main", "master" ] # Roda sempre que você der push

jobs:
  build:
    runs-on: windows-latest # Usa uma máquina Windows oficial

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Gerar EXE com PyInstaller
      run: |
        # Usamos ";" porque a máquina do GitHub é Windows
        pyinstaller --noconfirm --onefile --windowed --add-data "dataset;dataset" --name "MacroIA_Universal" Macro.py

    - name: Criar ZIP e Disponibilizar
      uses: actions/upload-artifact@v4
      with:
        name: Pacote-Macro-Windows
        path: dist/MacroIA_Universal.exe
